<?xml version="1.0" encoding="utf-8"?><Database Name="QL_ShopQuanAo" Class="ShopQuanAoDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=LAPTOP-0T0KM268;Initial Catalog=QL_ShopQuanAo;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QL_ShopQuanAoConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ChiTietDonHang" Member="ChiTietDonHangs">
    <Type Name="ChiTietDonHang">
      <Column Name="MaChiTietDonHang" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaDonHang" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GiaDonVi" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MaSize" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="DonHang" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="DonHang_ChiTietDonHang1" Member="DonHang1" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="DonHang" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="SanPham_ChiTietDonHang1" Member="SanPham1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="Size_ChiTietDonHang" Member="Size" ThisKey="MaSize" OtherKey="MaSize" Type="Size" IsForeignKey="true" />
      <Association Name="Size_ChiTietDonHang1" Member="Size1" ThisKey="MaSize" OtherKey="MaSize" Type="Size" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhGia" Member="DanhGias">
    <Type Name="DanhGia">
      <Column Name="MaDanhGia" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DanhGia" Member="DanhGia1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NoiDung" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NgayDanhGia" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="KhachHang_DanhGia" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="TenDangNhap" Type="KhachHang" IsForeignKey="true" />
      <Association Name="KhachHang_DanhGia1" Member="KhachHang1" ThisKey="MaKhachHang" OtherKey="TenDangNhap" Type="KhachHang" IsForeignKey="true" />
      <Association Name="SanPham_DanhGia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="SanPham_DanhGia1" Member="SanPham1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DanhMuc" Member="DanhMucs">
    <Type Name="DanhMuc">
      <Column Name="MaDanhMuc" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenDanhMuc" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="DanhMuc_SanPham" Member="SanPhams" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="SanPham" />
      <Association Name="DanhMuc_SanPham1" Member="SanPhams1" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.DonHang" Member="DonHangs">
    <Type Name="DonHang">
      <Column Name="MaDonHang" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaKhachHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NgayDat" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DiaChiGiaoHang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TrangThaiDonHang" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="DonHang_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="DonHang_ChiTietDonHang1" Member="ChiTietDonHangs1" ThisKey="MaDonHang" OtherKey="MaDonHang" Type="ChiTietDonHang" />
      <Association Name="KhachHang_DonHang" Member="KhachHang" ThisKey="MaKhachHang" OtherKey="TenDangNhap" Type="KhachHang" IsForeignKey="true" />
      <Association Name="KhachHang_DonHang1" Member="KhachHang1" ThisKey="MaKhachHang" OtherKey="TenDangNhap" Type="KhachHang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.KhachHang" Member="KhachHangs">
    <Type Name="KhachHang">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="DiaChi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ThanhPho" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Tinh" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MaZip" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="KhachHang_DanhGia" Member="DanhGias" ThisKey="TenDangNhap" OtherKey="MaKhachHang" Type="DanhGia" />
      <Association Name="KhachHang_DanhGia1" Member="DanhGias1" ThisKey="TenDangNhap" OtherKey="MaKhachHang" Type="DanhGia" />
      <Association Name="KhachHang_DonHang" Member="DonHangs" ThisKey="TenDangNhap" OtherKey="MaKhachHang" Type="DonHang" />
      <Association Name="KhachHang_DonHang1" Member="DonHangs1" ThisKey="TenDangNhap" OtherKey="MaKhachHang" Type="DonHang" />
      <Association Name="UserAccount_KhachHang" Member="UserAccount" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="UserAccount" IsForeignKey="true" />
      <Association Name="UserAccount_KhachHang1" Member="UserAccount1" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.MaGiamGia" Member="MaGiamGias">
    <Type Name="MaGiamGia">
      <Column Name="MaGiamGia" Member="MaGiamGia1" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="PhanTramGiam" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="NgayBatDau" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NgayKetThuc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="MaGiamGia_SanPhamMaGiamGia" Member="SanPhamMaGiamGias" ThisKey="MaGiamGia1" OtherKey="MaGiamGia" Type="SanPhamMaGiamGia" />
      <Association Name="MaGiamGia_SanPhamMaGiamGia1" Member="SanPhamMaGiamGias1" ThisKey="MaGiamGia1" OtherKey="MaGiamGia" Type="SanPhamMaGiamGia" />
    </Type>
  </Table>
  <Table Name="dbo.NhanVien" Member="NhanViens">
    <Type Name="NhanVien">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ho" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ten" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="DienThoai" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="UserAccount_NhanVien" Member="UserAccount" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="UserAccount" IsForeignKey="true" />
      <Association Name="UserAccount_NhanVien1" Member="UserAccount1" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="UserAccount" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPham" Member="SanPhams">
    <Type Name="SanPham">
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenSanPham" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="GioiTinh" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="MaDanhMuc" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MaThuongHieu" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Gia" Type="System.Decimal" DbType="Decimal(10,2)" CanBeNull="true" />
      <Column Name="MoTa" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Anh" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TrangThai" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="SanPham_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDonHang" />
      <Association Name="SanPham_ChiTietDonHang1" Member="ChiTietDonHangs1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="ChiTietDonHang" />
      <Association Name="SanPham_DanhGia" Member="DanhGias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="DanhGia" />
      <Association Name="SanPham_DanhGia1" Member="DanhGias1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="DanhGia" />
      <Association Name="SanPham_SanPhamMaGiamGia" Member="SanPhamMaGiamGias" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPhamMaGiamGia" />
      <Association Name="SanPham_SanPhamMaGiamGia1" Member="SanPhamMaGiamGias1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPhamMaGiamGia" />
      <Association Name="SanPham_Size" Member="Sizes" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="Size" />
      <Association Name="SanPham_Size1" Member="Sizes1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="Size" />
      <Association Name="DanhMuc_SanPham" Member="DanhMuc" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" />
      <Association Name="DanhMuc_SanPham1" Member="DanhMuc1" ThisKey="MaDanhMuc" OtherKey="MaDanhMuc" Type="DanhMuc" IsForeignKey="true" />
      <Association Name="ThuongHieu_SanPham" Member="ThuongHieu" ThisKey="MaThuongHieu" OtherKey="MaThuongHieu" Type="ThuongHieu" IsForeignKey="true" />
      <Association Name="ThuongHieu_SanPham1" Member="ThuongHieu1" ThisKey="MaThuongHieu" OtherKey="MaThuongHieu" Type="ThuongHieu" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SanPhamMaGiamGia" Member="SanPhamMaGiamGias">
    <Type Name="SanPhamMaGiamGia">
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaGiamGia" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="MaGiamGia_SanPhamMaGiamGia" Member="MaGiamGia1" ThisKey="MaGiamGia" OtherKey="MaGiamGia1" Type="MaGiamGia" IsForeignKey="true" />
      <Association Name="MaGiamGia_SanPhamMaGiamGia1" Member="MaGiamGia2" ThisKey="MaGiamGia" OtherKey="MaGiamGia1" Type="MaGiamGia" IsForeignKey="true" />
      <Association Name="SanPham_SanPhamMaGiamGia" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="SanPham_SanPhamMaGiamGia1" Member="SanPham1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Size" Member="Sizes">
    <Type Name="Size">
      <Column Name="MaSize" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MaSanPham" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MoTaSize" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SoLuong" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Size_ChiTietDonHang" Member="ChiTietDonHangs" ThisKey="MaSize" OtherKey="MaSize" Type="ChiTietDonHang" />
      <Association Name="Size_ChiTietDonHang1" Member="ChiTietDonHangs1" ThisKey="MaSize" OtherKey="MaSize" Type="ChiTietDonHang" />
      <Association Name="SanPham_Size" Member="SanPham" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
      <Association Name="SanPham_Size1" Member="SanPham1" ThisKey="MaSanPham" OtherKey="MaSanPham" Type="SanPham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ThuongHieu" Member="ThuongHieus">
    <Type Name="ThuongHieu">
      <Column Name="MaThuongHieu" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TenThuongHieu" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="ThuongHieu_SanPham" Member="SanPhams" ThisKey="MaThuongHieu" OtherKey="MaThuongHieu" Type="SanPham" />
      <Association Name="ThuongHieu_SanPham1" Member="SanPhams1" ThisKey="MaThuongHieu" OtherKey="MaThuongHieu" Type="SanPham" />
    </Type>
  </Table>
  <Table Name="dbo.UserAccount" Member="UserAccounts">
    <Type Name="UserAccount">
      <Column Name="TenDangNhap" Type="System.String" DbType="NVarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="MatKhau" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ChucVu" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Association Name="UserAccount_KhachHang" Member="KhachHang" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="KhachHang" Cardinality="One" />
      <Association Name="UserAccount_KhachHang1" Member="KhachHang1" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="KhachHang" Cardinality="One" />
      <Association Name="UserAccount_NhanVien" Member="NhanVien" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="NhanVien" Cardinality="One" />
      <Association Name="UserAccount_NhanVien1" Member="NhanVien1" ThisKey="TenDangNhap" OtherKey="TenDangNhap" Type="NhanVien" Cardinality="One" />
    </Type>
  </Table>
</Database>